### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cydral**
New model for gender classification.

### CODE REVIEW

**Comment by davisking** [comment]
Thanks for the PR :)

I assume you meant to include the model and example program that runs it as well? :)

**Comment by Cydral** [comment]
Yes, of course. I'm completing the model tests to check if everything is going well. I'll send you the additional information quickly.

**Comment by Cydral** [comment]
Hi Davis, the DNN model is here: https://github.com/Cydral/dlib-models/blob/patch-1/dnn_gender_classifier_v1.dat.bz2
For the test program, I propose this file: https://github.com/Cydral/dlib-models/blob/patch-1/dnn_gender_classifier_v1_ex.cpp
Thanks.

**Comment by Cydral** [comment]
Hi Davis, I also added a new CNN model for age prediction.

**Comment by davisking** [comment]
This is cool.  Can you put these things in a sub folder to make the association between the models and .cpp files that run them obvious? Also, please add some comments to the readme about license or how these models may be used. For example, can they be used for anything, in commercial applications, only in other open source?

**Comment by Arqenza** [comment]
Hi, Davis
I am always grateful to "Dlib".
I'm glad you like Asian images.
However, since the people in the picture are famous actors, all rights will not be granted.
Instead, there are copyright-free images available for commercial use. Would you like this image too?
asia1

**Comment by davisking** [comment]
Sorry, I meant to direct that question at @Cydral. Specifically about the licensing for the models.

**Comment by Arqenza** [comment]
I added the code to "dnn_gender_classifier" and got the result I think is correct.

>		if (p(0) < p(1))
>		{
>			gender = male_label;
>			confidence = p(1);
>		}
>		else
>		{
>			gender = female_label;  // <-- Is this not necessary?
>			confidence = p(0);
>		}
> 

Release>dnn_gender_classifier --test-image face1.png
face#0 - detected gender: female [100.0%]
face#1 - detected gender: female [100.0%]
face#2 - detected gender: male [100.0%]
face#3 - detected gender: female [100.0%]
face#4 - detected gender: female [100.0%]
face#5 - detected gender: female [100.0%]
face#6 - detected gender: male [99.9%]
face#7 - detected gender: female [100.0%]
face#8 - detected gender: female [99.9%]
face#9 - detected gender: female [100.0%]
face#10 - detected gender: male [99.9%]
face#11 - detected gender: female [100.0%]
face#12 - detected gender: female [100.0%]
face#13 - detected gender: male [99.9%]
face#14 - detected gender: male [92.0%]
face#15 - detected gender: male [99.7%]

**Comment by Cydral** [comment]
Hi @arqenza ,

Yes, I indeed found an issue in the loop and fixed it in the test program. So, the "gender = female_label" is necessary in the else part. In the meantime, I have checked again (it's a long journey...) the learning base and found some errors that are being corrected. I will give an improved version of the model again in a few days. If you find any classification errors, please do not hesitate to report them directly to me. Thank you!

**Comment by Cydral** [comment]
Hi @davisking ,

Np to isolate in dedicated directories the models and programs to test. I am doing that today. Otherwise, I updated the test programs to mention that the models are under the license of the other Dlib models, so the "Creative Commons Zero v1.0 Universal". I will do the same in the "Readme" file.

**Comment by Arqenza** [comment]
Thank you for your reply.
I support your wonderful work.

**Comment by Oktai15** [comment]
Any update?

**Comment by Cydral** [comment]
@Oktai15, I released the both new models for Dlib which seem to give good results in most cases. @Davis can merge these elements now.

**Comment by davisking** [comment]
Awesome.  I'll merge the PR when it's all ready to go.

These are the files in this diff:
```
 README.md                                          |  12 +++++
 age-predictor/dnn_age_predictor_v1.dat.bz2         | Bin 0 -> 10263707 bytes
 age-predictor/dnn_age_predictor_v1_ex.cpp          | 197 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 dnn_age_predictor_v1.dat.bz2                       | Bin 0 -> 10263707 bytes
 dnn_age_predictor_v1_ex.cpp                        | 194 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 dnn_gender_classifier_v1.dat.bz2                   | Bin 0 -> 509344 bytes
 dnn_gender_classifier_v1_ex.cpp                    | 274 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 gender-classifier/dnn_gender_classifier_v1.dat.bz2 | Bin 0 -> 513072 bytes
 gender-classifier/dnn_gender_classifier_v1_ex.cpp 
```
I was going to delete the files outside the sub folders but some files are duplicates and others are not.  Are the files outside the sub folders the old files that should be deleted?  Please update the PR to not contain duplicated files.
```
davis@flat:~/temp/dlib-models$ md5sum dnn_gender_classifier_v1* gender-classifier/* | sort
253f6b75e9a1c77d5ffd54cfb43f6fca  gender-classifier/dnn_gender_classifier_v1.dat.bz2
4b3913c21f42781543acb701bef63601  dnn_gender_classifier_v1.dat.bz2
56b5b4ee30ca52358a67acfaa2214456  dnn_gender_classifier_v1_ex.cpp
7fc93df1248b101277a1ed7519e70f39  gender-classifier/dnn_gender_classifier_v1_ex.cpp
davis@flat:~/temp/dlib-models$ md5sum dnn_age_predictor_v1* age-predictor/* | sort
1348a7f711e1b1a6d26c1d091cfa12dc  dnn_age_predictor_v1_ex.cpp
4a6fc4e77dd1472480739ce79db9d24a  age-predictor/dnn_age_predictor_v1.dat.bz2
4a6fc4e77dd1472480739ce79db9d24a  dnn_age_predictor_v1.dat.bz2
ea61f7f331b0d7b6fda83f50113110c6  age-predictor/dnn_age_predictor_v1_ex.cpp
```

**Comment by Cydral** [comment]
Hi @davisking , I'm sorry for the delay. That's correct and as you asked for, I copied all the stuff in a sub folder to simplify the merging. The most recent versions are therefore in the subdirectory. The README file at root, on the other hand, directly integrates the details of the two new models.

**Comment by davisking** [comment]
No worries, thanks for the PR :)

**Pull request merged**
