### PR TITLE
New DNN model for facial recognition

### PR DESCRIPTION
**Pull request by Cydral**
New facial recognition model added.

### CODE REVIEW

**Comment by davisking** [comment]
Nice, that's cool :D

**Comment by TaguchiModels** [comment]
> New facial recognition model added.

## Face recognition model with Asian (mainly Japanese) added

I collected many datasets, mainly Japanese, and trained from scratch. Even though it was trained for Japanese people, the results are comparable to the dlib model when it comes to facial recognition for Western people. Photos of Hollywood action heroes provided in the dlib example can also be classified in the same way as dlib.
I tested the accuracy with the LFW dataset to present some objectivity.
The result was 0.9895%.
In total, I used over 6.5 million faces from over 16,000 people to train my facial recognition model.
Approximately 47% of this is facial data of Japanese people (including some Asian people other than Japanese).

[Taguchi models](https://github.com/TaguchiModels/dlibModels/blob/main/README_EN.md)

[taguchi_face_recognition_resnet_model_v1.zip](https://github.com/davisking/dlib-models/files/15284958/taguchi_face_recognition_resnet_model_v1.zip)

**Comment by TaguchiModels** [comment]
It seems that I don't have the permission to merge, so I can't determine whether I should just wait.
If you have any advice, please let me know.

**Comment by davisking** [comment]
Yeah you just need to make a new pull request with what you want to merge and then I click a button and it gets merged.

**Pull request merged**
